steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/gcloud-kubectl-helm','.' ]

images:
- eu.gcr.io/$PROJECT_ID/gcloud-kubectl-helm

options:
  env:
    - PROJECT_ID=urbansportsclub-dev
